# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ex-lib-zip
version:      0.04
version_from: zip.pm
installdirs:  site
requires:
    PerlIO::gzip:                  0.07
    PerlIO::subfile:               0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
